### ISSUE TITLE
Ignore automatically generated migrations

### ISSUE THREAD

**Issue by michaelcullum** [schmittjoh/php-code-analysis#36]
Clutters up the auto-changed files with migrations namespace use statements changing:

`````` 5
-use Doctrine\DBAL\Migrations\AbstractMigration,
6       
-    Doctrine\DBAL\Schema\Schema;
5   
+use Doctrine\DBAL\Migrations\AbstractMigration;
6   
+use Doctrine\DBAL\Schema\Schema;```

Should probably just ignore migrations files as they are automatically generated?
``````

**Comment by schmittjoh** [comment]
You could either turn these fixes off for certain files,

``` yml
# .jms.yml
path_configs:
    migrations:
        paths: [app/DoctrineMigrations/*]
        use_statement_fixes: false
```

or, you could also set it to preserve multiple statements like (`use A, B;`):

``` yml
# .jms.yml
default_config:
    use_statement_fixes:
        preserve_multiple: true
```

There are some more settings in the docs: http://jmsyst.com/automated-code-reviews/docs

I'm not sure if we can do something better by default which makes everyone happy.
